/**
 * MVEE Song Catalogue — Cosmic ambient soundtrack
 *
 * Style: otherworldly, vast, contemplative. Think Outer Wilds, FTL,
 * or Dwarf Fortress ambient. Not fantasy-medieval like Creatures.
 *
 * Filenames must match audio files generated by ElevenLabs and deployed
 * to /mvee/audio/ on the play site (must be under /mvee/ prefix for Traefik routing).
 */

import type { SongEntry } from '../lore/SongSystem.js';

export const MVEE_SONG_CATALOGUE: readonly SongEntry[] = [
  // Event-driven tracks only — ambient drone tracks removed (board directive: no generative tones)
  // Grief (2 tracks)
  { filename: 'Last Light.mp3', occasion: 'grief' },
  { filename: 'Fading Echo.mp3', occasion: 'grief' },
  // Elder (2 tracks)
  { filename: 'Ancient Wisdom.mp3', occasion: 'elder' },
  { filename: 'Starborn Memory.mp3', occasion: 'elder' },
  // Warning (1 track)
  { filename: 'Dark Horizon.mp3', occasion: 'warning' },
  // Hearth (1 track)
  { filename: 'Hearthglow.mp3', occasion: 'hearth' },
  // Birth (1 track)
  { filename: 'New Dawn.mp3', occasion: 'birth' },
] as const;
