/**
 * MVEE Song Catalogue — Cosmic ambient soundtrack
 *
 * Style: otherworldly, vast, contemplative. Think Outer Wilds, FTL,
 * or Dwarf Fortress ambient. Not fantasy-medieval like Creatures.
 *
 * Filenames must match audio files generated by ElevenLabs and deployed
 * to /audio/mvee/ on the play site.
 */

import type { SongEntry } from '../lore/SongSystem.js';

export const MVEE_SONG_CATALOGUE: readonly SongEntry[] = [] as const;
